import sqlite3

scenarios = [

    'Air traffic Control',
    'Appliance control (lighting and HVAC)',
    'Area and theater monitoring (military)',
    'Assembly line and workflow',
    'Asset management (e.g., container tracking)',
    'Automated automobile maintenance telemetry',
    'Automatic control of multiple home systems to improve conservation, convenience, and safety',
    'Automatic meter reading',
    'Automating control of multiple systems to improve conservation, flexibility, and security',
    'Automotive sensors and actuators',
    'Auto-to-auto applications (FCC recently approved specific frequencies for highway sensor',
    'and auto-to-auto applications; range is about 100 m [2.55])',
    'Battlefield management',
    'Battlefield reconnaissance and surveillance',
    'Biological monitoring for agents',
    'Biomedical applications',
    'Blinds, drapery, and shade controls',
    'Body-worn medical sensors',
    'Borders monitoring (Mexican and Canadian borders)',
    'Bridge and highway monitoring (safety)',
    'Building and structures monitoring',
    'Building automation (security,HVAC, automated meter reading, lighting control, access control)',
    'Building energy monitoring and control',
    'Capturing highly detailed electric, water, and gas utility usage data',
    'Centibots (DARPA): embedded mobile sensor nodes; 100 robots mapping, tracking, and',
    'guarding an environment in a coherent manner',
    'Chemical, biological, radiological, and nuclear wireless sensors (sensors for toxic chemicals,',
    'explosives, and biological agents)',
    'Civil engineering applications',
    'Collection of long-term databases of clinical data (enables correlation of biosensor readings',
    'with other patient information)',
    'Combat field surveillance',
    'Commercial applications',
    'Commercial building control',
    'Configuring and running multiple home control systems from a single remote control',
    'Consumer applications',
    'Consumer electronics and entertainment (TV, VCR, DVD/CD)',
    'Consumers’ ability to keep track of their belongings, pets, and young children',
    'Control of temperature',
    'Controlling the spread of wild fires',
    'Critical infrastructure protection and security',
    'Defense systems',
    'Detecting an impulsive event (e.g., a footstep or gunshot) or vehicle (e.g., wheeled or tracked,',
    'light or heavy)',
    'Detecting structural faults in aircraft',
    'Detecting structural faults in buildings (e.g., fatigue-induced cracks)',
    'Detecting structural faults in ships',
    'Detecting toxic agents',
    'Detection and tracking of enemy vehicles',
    'Disaster management',
    'Distributed robotics',
    'Distributed sensing (military)',
    'Earthquake detection',
    'Electricity load management',
    'Embedding intelligence to optimize consumption of natural resources',
    'E-money/point-of-sale applications (including kiosks)',
    'Enabling businesses to monitor and control workspaces',
    'Enabling deployment of wireless monitoring networks to enhance perimeter protection',
    'Enabling extension and upgrading of building infrastructure with minimal effort',
    'Enabling installation, upgrading, and networking of home control system without wires',
    'Enabling networking and integration of data from multiple access control points',
    'Enabling rapid reconfiguring of lighting systems to create adaptable workspaces',
    'Energy management',
    'Environmental (land, air, sea) and agricultural wireless sensors',
    'Environmental control (e.g., tracking soil contamination, habitat monitoring)',
    'Environmental monitoring, including precision agriculture',
    'Environmental sensing applications',
    'Equipment management services and preventive maintenance',
    'Extending existing manufacturing and process control systems reliably',
    'Facilitating the reception of automatic notification upon detection of unusual events',
    'Farm sensor and actuator networks (monitoring soil moisture, feeding pigs, unmanned',
    'tractor control)',
    'Flexible management of lighting, heating, and cooling systems from anywhere in the home',
    'Food safety',
    'Gas, water, and electric meters',
    'Gateway or field service links to sensors and equipment (monitored to support preventive',
    'maintenance, status changes, diagnostics, energy use, etc.)',
    'Habitat monitoring',
    'Habitat sensing',
    'Health care',
    'Heartbeat sensors',
    'Heating control',
    'Helping automate data acquisition from remote sensors to reduce user intervention',
    'Helping deploy monitoring networks to enhance employee and public safety',
    'Helping identify inefficient operation or poorly performing equipment',
    'Helping streamlining data collection for improved compliance reporting',
    'Herd control from central location using sensor-based fences and remote-controlled gates',
    'Home automation, including alarms (e.g., an alarm sensor that triggers a call to a security firm)',
    'Home control applications to provide control, conservation, convenience, and safety',
    'Home monitoring for chronic and elderly patients (collection of periodic or continuous data',
    'and upload to physicians)',
    'Home security',
    'Homeland Security Advanced Research Projects Agency, which has the goal of developing a',
    'national sensor net to detect biological, chemical, and nuclear agents',
    'Hotel energy management',
    'HVAC control',
    'iBadge (UCLA): used to track the behavior of children or patients (e.g., speech',
    'recording/replaying, position detection, direction detection, local climate:',
    'temperature, humidity, pressure)',
    'iButton: a small computer chip enclosed in a stainless steel container that looks like a',
    'button containing up-to-date information that can travel with a person or object',
    '(e.g., be used wirelessly with an ATM or vending machine)',
    'IEEE 802.15.4 mote (Telos is first 802.15.4-based mote; 2/2004; www.moteiv.com)',
    'Improving asset management by continuous monitoring of critical equipment',
    'Industrial and building automation',
    'Industrial and building monitoring',
    'Industrial and manufacturing automation',
    'Industrial automation applications that provide control, conservation, and efficiency',
    'Industrial control (asset management, process control, environmental, energy management)',
    'Industrial monitoring and control',
    'Integrating and centralizing management of lighting, heating, cooling, and security',
    'Intrusion detection',
    'Inventory control',
    'Inventory management',
    'Law enforcement',
    'Lighting control',
    'Localization',
    'Manufacturing control',
    'Mass-casualties management',
    'Materials processing systems (heat, gas flow, cooling, chemical)',
    'Medical disaster response',
    'Medical sensing and monitoring',
    'Metropolitan operations (traffic, automatic tolls, fire, etc.)',
    'Microclimate assessment and monitoring',
    'Military applications',
    'Military command, control, communications, intelligence, and targeting systems',
    'Military sensing',
    'Military sensor networks to detect and gain information about enemy movements',
    'Military tactical surveillance',
    'Military vigilance for unknown troop and vehicle activity',
    'Mobile robotics',
    'Monitoring and controlling cities',
    'Monitoring and controlling factories',
    'Monitoring and controlling homes',
    'Monitoring and controlling offices',
    'Monitoring and controlling the ambiance',
    'Monitoring and controlling the environment',
    'Monitoring and controlling vehicles',
    'Monitoring animal populations',
    'Monitoring complex machinery and processes/condition-based maintenance (CBM)',
    'Monitoring for explosives',
    'Monitoring for toxic chemicals',
    'Monitoring intersections',
    'Monitoring on-truck and on-ship tamper of assets',
    'Monitoring rooftops (military)',
    'Monitoring the limb movements and muscle activity of stroke patients during rehabilitation',
    'exercise',
    'Monitoring the security of civil and engineering infrastructures',
    'Monitoring wild fires',
    'Nanoscopic sensor applications (e.g., biomedics)',
    'National defense',
    'National security',
    'Near field communication (NFC) as a ‘‘virtual connector’’ (NFC acts like RFID but requires',
    'close proximity to read, providing easy identification and security; wireless connectivity',
    'needed to transport data [2.55,2.58])',
    'Nose-on-a-chip (Oak Ridge National Laboratory): a MEMS-based sensor that can detect 400',
    'types of gases and transmit information to a central control station, indicating the level',
    'Perimeter security',
    'Personal health diagnosis',
    'Personal health care (patient monitoring, fitness monitoring)',
    'Pervasive computing (‘‘invisible computing,’’ ‘‘ubiquitous computing’’)',
    'Physical security',
    'Pre-hospital and in-hospital emergency care',
    'Preventive maintenance for equipment used by a semiconductor fabricator',
    'Process control',
    'Production processing',
    'Providing detailed data to improve preventive maintenance programs',
    'Public assembly locations monitoring',
    'Public-safety applications',
    'Quality-of-life applications',
    'Radar used to profile soil composition in vineyards (UC–Berkeley)',
    'Radiation and nuclear-threat detection systems',
    'Real-time collection of data (e.g., to check temperature or monitor pollution levels)',
    'Real-time continuous patient monitoring (e.g., pre-hospital, in-hospital, and ambulatory',
    'monitoring)',
    'Reducing energy costs through optimized manufacturing processes',
    'Reducing energy expenses through optimized HVAC management',
    'Refrigeration cage or appliance monitoring',
    'Remote underwater sampling station (RUSS) robots used to monitor municipal water',
    'supplies; the WNs are solar-powered robots that float on the surface and deploy',
    'descendable sensors underwater to sample temperature, oxygen, turbidity, light, and salt',
    'content; data are transmitted by cell phone to central lab and posted on the Web [2.55]',
    'Remotely-controlled home heating and lighting',
    'Remotely monitored assets, billing, and energy management',
    'Residential control and monitoring applications',
    'Residential/light commercial control (security, HVAC, lighting control, access control,',
    'lawn and garden irrigation)',
    'RF-based localization',
    'RFID tags',
    'Ring sensor (MIT): monitors the physiological status of the wearer and transmits the',
    'information to a medical professional over the Internet',
    'Routing, naming, discovery, and security for wireless medical sensors, personal digital',
    'assistants, PCs, and other devices',
    'Scientific applications',
    'Security services (including peel-n’-stick security sensors)',
    'Seismic accelerometers (devices able to measure movement)',
    'Sensor networks for theme parks',
    'Sensor networks to detect and characterize chemical, biological, radiological, nuclear, and',
    'explosive attacks and material',
    'Sensor networks to detect and monitor environmental changes in plains, forests, and oceans',
    'Sensors embedded in a glacier in Norway (pelletlike WNs are embedded 60 m inside a glacier',
    'and use collaborative methods to collect and transmit data) [2.55]',
    'Sensors in chimneys to monitor creosote buildup',
    'Smart bullet fired from a paintball gun (wireless transmitter and battery capable of a range of',
    '70 m) [2.57]',
    'Smart bricks: accelerometer/thermistor/etc. embedded in bricks (UIUC)',
    'Smart kindergarten project (Mani Srivastava/UCLA): I-badges embedded in children’s hats',
    'to track position, bearing, and record sound; classroom toys have sensors embedded',
    'to detect use',
    'Smart structures that are able to self-diagnose potential problems and self-prioritize requisite',
    'repairs',
    'Smoke, CO, and H2O detectors',
    'Stroke patient rehabilitation',
    'Supermarket management',
    'Supporting the straightforward installation of wireless sensors to monitor a wide variety',
    'of conditions',
    'Telemedicine',
    'Toxin detection',
    'Tracing source of contamination',
    'Tracking criminals',
    'Tracking endangered species',
    'Tracking wild fires',
    'Traffic light sensors and control (using distributed greedy algorithms) [2.56]',
    'Traffic flow and surveillance',
    'Tsunami alerting',
    'Turf cam microcameras (about 0.5 cm3) placed throughout a football field [2.55]',
    'Underfloor air distribution systems',
    'Universal remote control to a set-top box',
    'Vehicle tracking',
    'Video surveillance',
    'Virtual fence using a sensor or actuator as a collar (Dartmouth College is using Wi-Fi',
    'PDA collars)',
    'Vital sign data, such as pulse oximetry and two-lead EKG (medical)',
    'Volcanic eruptions',
    'Warehouse inventory',
    'Warehouses, fleet management, factory, supermarkets, and office complexes',
    'Water supply protection (detecting poisons such as ricin and other pathogens)',
    'via microfluidics and WSN-based sensors',
    'Weapon sensors for ships',
    'Weather monitoring',
    'Weather sensing',
    'Wi-Fi tags to track children [2.55]',
    'Wildfire tracking and monitoring',
    'Wireless automated meter reading and load management',
    'Wireless lighting control (e.g., dimmable ballasts, controllable light switches,',
    'customizable lighting schemes, energy savings on bright days)',
    'Wireless parking lot sensor networks to determine which parking spots are available',
    'Wireless smoke and CO detectors',
    'Wireless surveillance sensor networks for providing security in shopping malls and',
    'parking garages',
    'Wireless traffic sensor networks to monitor vehicle traffic on highways or in',
    'congested locations',
    'WolfPack (DARPA): distributed sensing and radio jamming device (a soda-can-sized pod',
    'deployed about 1 per 1 km2 is designed to replace or supplement similar technologies',
    'that currently reside in aircraft; because of proximity to enemy radios, less power is',
    'required to jam signals; adhoc networking and multihop routing are used to control and',
    'retrieve data from the network, which can also monitor enemy communications in addition',
    'to jamming them; pods are designed to last for about two months) [2.55,2.59]',
    'Workplace applications',
    'WSN-based data logger system for redwood monitoring; 50 nodes installed by',
    'UC–Berkeley at UC Botanical Gardens',
    'WSNs for winemaking: UC–Berkeley motes for real-time mesoclimate',
    'monitoring and historical analysis [2.55]'
]

conn = sqlite3.connect('../AlgorithmStore.db')
c = conn.cursor()
c.execute('DELETE FROM ml_scenarios')

for scenario in scenarios:
    insert_q = "INSERT INTO ml_scenarios(scenario_name) VALUES ('{}')".format(scenario)
    c.execute(insert_q)

conn.commit()
conn.close()
