
class ParamValues:

	class NAME_EARTHQUAKE:
		DETECTION = "earthquake detection"
		MONITORING = "earthquake monitoring"

	class NAME_UNDERWATER:
		DETECTION = "underwater detection"
		MONITORING = "underwater monitoring"

	class NAME_FORESTFIRE:
		DETECTION = "forestfire detection"
		MONITORING = "forestfire monitoring"

	class NAME_TSUNAMI:
		DETECTION = "tsunami detection"
		MONITORING = "tsunami monitoring"

	class NAME_BODYHEALTH:
		MONITORING = "bodyhealth monitoring"

	class NAME_SURVEILLANCE:
		DETECTION = "surveillance detection"
		MONITORING = "surveillance monitoring"


	PARAM_COMMS_ALGO_HIERARCHICAL = "hierarchical"
	PARAM_COMMS_ALGO_FLOODING = "flooding"
	PARAM_COMMS_ALGO_DIFFUSION = "diffusion"

	PARAM_SENSING_TRIGGER_BY_QUERY = "query"
	PARAM_SENSING_TRIGGER_BY_EVENT = "event"
	PARAM_SENSING_TRIGGER_BY_CONTINUOUS = "continuous"

	PARAM_AGGREGATION_TYPE_PUSH = "push"
	PARAM_AGGREGATION_TYPE_PULL = "pull"
	PARAM_AGGREGATION_TYPE_HYBRID = "hybrid"

	PARAM_PHYSICAL_NETWORK_TOPO_STAR = "star"
	PARAM_PHYSICAL_NETWORK_TOPO_LINEAR = "linear"
	PARAM_PHYSICAL_NETWORK_TOPO_MESH = "mesh"
	PARAM_PHYSICAL_NETWORK_TOPO_BUS = "bus"
	PARAM_PHYSICAL_NETWORK_TOPO_RING = "ring"
	PARAM_PHYSICAL_NETWORK_TOPO_HYBRID = "hybrid"

	PARAM_PHYSICAL_SENSOR_TOPO_RANDOMSPARSE = "sparse"
	PARAM_PHYSICAL_SENSOR_TOPO_RANDOMDENSE = "dense"
	PARAM_PHYSICAL_SENSOR_TOPO_ORDEREDLINEAR = "linear"

	PARAM_SINK_REPORTING_ONE_TO_ONE = "one_to_one"
	PARAM_SINK_REPORTING_ONE_TO_MANY = "one_to_many"
	PARAM_SINK_REPORTING_MANY_TO_ONE = "many_to_one"
	PARAM_SINK_REPORTING_MANY_TO_MANY = "many_to_many"

	PARAM_REQUIRED_CONN_PARTIAL = "partial"
	PARAM_REQUIRED_CONN_FULL = "full"

	PARAM_HOPS_TO_SINK_MULTIHOP = "multihop"
	PARAM_HOPS_TO_SINK_SINGLEHOP = "singlehop"

	PARAM_EVENT_STATE_DETECTION = "detection"
	PARAM_EVENT_STATE_TRACKING = "tracking"

	PARAM_PRIMARY_FEATURE_TEMPERATURE = "temperature"
	PARAM_PRIMARY_FEATURE_PRESSURE = "pressure"
	PARAM_PRIMARY_FEATURE_VIBRATION = "vibration"
	PARAM_PRIMARY_FEATURE_WATER_LEVEL = "water_level"

	PARAM_PRIMARY_MEDIUM_SOLID = "solid"
	PARAM_PRIMARY_MEDIUM_LIQUID = "liquid"
	PARAM_PRIMARY_MEDIUM_GAS = "gas"

	PARAM_AGGREG_ALGORITHM_SUM = "sum"
	PARAM_AGGREG_ALGORITHM_DIV = "div"
	PARAM_AGGREG_ALGORITHM_MAX = "max"
	PARAM_AGGREG_ALGORITHM_MIN = "min"
	PARAM_AGGREG_ALGORITHM_AVG = "avg"
	PARAM_AGGREG_ALGORITHM_COUNT = "count"

	PARAM_BEST_TECHNIQUE_LEACH = "leach"
	PARAM_BEST_TECHNIQUE_HEED = "heed"
	PARAM_BEST_TECHNIQUE_PEGASIS = "pegasis"
	PARAM_BEST_TECHNIQUE_DBST = "dbst"
	PARAM_BEST_TECHNIQUE_DIRECTEDDIFFUSION = "directed_diffusion"

	PARAM_0_0 = '0'
	PARAM_0_1 = '0.1'
	PARAM_0_2 = '0.2'
	PARAM_0_4 = '0.4'
	PARAM_0_6 = '0.6'
	PARAM_0_8 = '0.8'
	PARAM_1_0 = '1.0'


class WSNAttributes:
	AGGREG_ALGORITHM = 'AGGREG_ALGORITHM'
	COMMUNICATION_ALGORITHM = 'COMMUNICATION_ALGORITHM'
	REQUIRED_CONNECTIVITY = 'REQUIRED_CONNECTIVITY'
	SENSING_TRIGGER = 'SENSING_TRIGGER'
	PHYSICAL_SENSOR_TOPOLOGY = 'PHYSICAL_SENSOR_TOPOLOGY'
	PHYSICAL_NETWORK_TOPOLOGY = 'PHYSICAL_NETWORK_TOPOLOGY'
	SINK_REPORTING_MODE = 'SINK_REPORTING_MODE'
	NAME = 'NAME'
	FIELD_SIZE = 'FIELD_SIZE'
	FIELD_SIZE_CHANGE = 'FIELD_SIZE_CHANGE'
	EVENT_STATE = 'EVENT_STATE'
	PRIMARY_FEATURE = 'PRIMARY_FEATURE'
	OBJECTIVE_ENERGY = 'OBJECTIVE_ENERGY'
	OBJECTIVE_BANDWIDTH = 'OBJECTIVE_BANDWIDTH'
	OBJECTIVE_LATENCY = 'OBJECTIVE_LATENCY'
	OBJECTIVE_ACCURACY = 'OBJECTIVE_ACCURACY'
	MIN_ENERGY_CONSUMPTION = 'MIN_ENERGY_CONSUMPTION'
	MAX_ENERGY_CONSUMPTION = 'MAX_ENERGY_CONSUMPTION'
	MIN_BANDWIDTH_CONSUMPTION = 'MIN_BANDWIDTH_CONSUMPTION'
	MAX_BANDWIDTH_CONSUMPTION = 'MAX_BANDWIDTH_CONSUMPTION'
	MIN_LATENCY = 'MIN_LATENCY'
	MAX_LATENCY = 'MAX_LATENCY'
	SAMPLING_RATE = 'SAMPLING_RATE'
	SPREAD_RATE = 'SPREAD_RATE'
	PRIMARY_MEDIUM = 'PRIMARY_MEDIUM'
	HOMOGENOUS_NODES = 'HOMOGENOUS_NODES'
	AGGREGATION_NODE_RATIO = 'AGGREGATION_NODE_RATIO'
	AGGREGATION_TYPE = 'AGGREGATION_TYPE'
	REPORTING_BY_PERIODIC = 'REPORTING_BY_PERIODIC'
	REPORTING_BY_EVENT = 'REPORTING_BY_EVENT'
	PERIODIC_MONITORING_BY_REALTIME = 'PERIODIC_MONITORING_BY_REALTIME'
	PERIODIC_MONITORING_BY_QUERY = 'PERIODIC_MONITORING_BY_QUERY'
	PERIODIC_MONITORING_BY_EVENT = 'PERIODIC_MONITORING_BY_EVENT'
	LOCATION_AWARENESS = 'LOCATION_AWARENESS'
	NODE_MOBILITY = 'NODE_MOBILITY'
	BEST_TECHNIQUE = 'BEST_TECHNIQUE'


class ScenarioStates:

	DETECTION = 'detection'
	TRACKING = 'tracking'

